# Generated by Django 5.2.7 on 2025-10-07 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_rename_priority_key"),
        ("tickets", "0013_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Clasificación opcional para agrupar respuestas y facilitar la búsqueda.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faqs",
                to="catalog.category",
            ),
        ),
    ]
