# Generated by Django 5.2.7 on 2025-10-16 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_subcategory"),
        ("tickets", "0019_ticket_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="catalog.subcategory",
            ),
        ),
    ]
