# Generated by Django 5.2.6 on 2025-10-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_faq_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('assign_ticket', 'Puede asignar ticket'), ('transition_ticket', 'Puede cambiar estado de ticket'), ('comment_internal', 'Puede comentar internamente'), ('view_all_tickets', 'Puede ver todos los tickets'), ('view_reports', 'Puede ver reportes'), ('manage_reports', 'Puede administrar reportes'), ('set_ticket_category', 'Puede seleccionar la categoría al crear o actualizar un ticket'), ('set_ticket_priority', 'Puede seleccionar la prioridad al crear o actualizar un ticket')]},
        ),
    ]
