# Generated by Django 5.2.8 on 2025-11-19 20:23

import tickets.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0023_extend_ticket_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Opcional: imagen ilustrativa (hasta 2 MB)",
                null=True,
                upload_to="faq/",
                validators=[tickets.validators.validate_faq_image],
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Opcional: video MP4 (hasta 25 MB)",
                null=True,
                upload_to="faq/",
                validators=[tickets.validators.validate_faq_video_file],
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
