# Generated by Django 6.0 on 2025-12-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0026_remove_ticket_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="code",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
