# Generated by Django 5.2.8 on 2025-11-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="is_critical",
            field=models.BooleanField(default=False),
        ),
    ]
