# Generated by Django 5.2.8 on 2025-11-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_critical_actor",
            field=models.BooleanField(
                default=False,
                help_text="Marca si el usuario actúa como gerente/actor crítico en tickets.",
            ),
        ),
    ]
