PERMISSION_LABELS = {
    "add_ticket": "Puede agregar ticket",
    "change_ticket": "Puede cambiar ticket",
    "delete_ticket": "Puede eliminar ticket",
    "view_ticket": "Puede ver ticket",
    "assign_ticket": "Puede asignar ticket",
    "transition_ticket": "Puede cambiar estado de ticket",
    "comment_internal": "Puede comentar internamente",
    "view_all_tickets": "Puede ver todos los tickets",
    "add_ticketcomment": "Puede agregar comentario",
    "change_ticketcomment": "Puede cambiar comentario",
    "delete_ticketcomment": "Puede eliminar comentario",
    "view_ticketcomment": "Puede ver comentario",
    "add_ticketattachment": "Puede agregar adjunto",
    "change_ticketattachment": "Puede cambiar adjunto",
    "delete_ticketattachment": "Puede eliminar adjunto",
    "view_ticketattachment": "Puede ver adjunto",
    "add_category": "Puede agregar categoría",
    "change_category": "Puede cambiar categoría",
    "delete_category": "Puede eliminar categoría",
    "view_category": "Puede ver categoría",
    "add_priority": "Puede agregar prioridad",
    "change_priority": "Puede cambiar prioridad",
    "delete_priority": "Puede eliminar prioridad",
    "view_priority": "Puede ver prioridad",
    "add_area": "Puede agregar área",
    "change_area": "Puede cambiar área",
    "delete_area": "Puede eliminar área",
    "view_area": "Puede ver área",
}
